// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZKIuuKqB6Bby-LUHPPEa27ngI7jn_GOk',
    appId: '1:691295757862:web:6a8efbdf30579cb80228e7',
    messagingSenderId: '691295757862',
    projectId: 'dispatch-rider-2fb16-b28e7',
    authDomain: 'dispatch-rider-2fb16-b28-59517.firebaseapp.com',
    storageBucket: 'dispatch-rider-2fb16-b28e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVCwUpDyOVO_wDhLrAgOGGJBdOK0qUXeI',
    appId: '1:691295757862:android:1c8c406cd522a7880228e7',
    messagingSenderId: '691295757862',
    projectId: 'dispatch-rider-2fb16-b28e7',
    storageBucket: 'dispatch-rider-2fb16-b28e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIdCVkU6YokC-ZHUdheqJmA0ds6hqNXRk',
    appId: '1:691295757862:ios:8fd1a222584937ae0228e7',
    messagingSenderId: '691295757862',
    projectId: 'dispatch-rider-2fb16-b28e7',
    storageBucket: 'dispatch-rider-2fb16-b28e7.firebasestorage.app',
    iosBundleId: 'com.example.dispatchRiderNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIdCVkU6YokC-ZHUdheqJmA0ds6hqNXRk',
    appId: '1:691295757862:ios:8fd1a222584937ae0228e7',
    messagingSenderId: '691295757862',
    projectId: 'dispatch-rider-2fb16-b28e7',
    storageBucket: 'dispatch-rider-2fb16-b28e7.firebasestorage.app',
    iosBundleId: 'com.example.dispatchRiderNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZKIuuKqB6Bby-LUHPPEa27ngI7jn_GOk',
    appId: '1:691295757862:web:ef5f9c004ee9b67c0228e7',
    messagingSenderId: '691295757862',
    projectId: 'dispatch-rider-2fb16-b28e7',
    authDomain: 'dispatch-rider-2fb16-b28-59517.firebaseapp.com',
    storageBucket: 'dispatch-rider-2fb16-b28e7.firebasestorage.app',
  );

}